In [2]:
import numpy as np

In [6]:
data1  = [2.0,4,5,2,1]

In [7]:
arr1 = np.array(data1)

In [8]:
arr1

array([2., 4., 5., 2., 1.])

In [9]:
data2 = [[54,6,34,23],[23,67,34,2
                      ]]

In [10]:
arr2 = np.array(data2)

In [11]:
arr2


array([[54,  6, 34, 23],
       [23, 67, 34,  2]])

In [12]:
arr2.ndim

2

In [13]:
arr2.shape

(2, 4)

In [14]:
arr2.dtype

dtype('int32')

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.empty((2,5,2))

array([[[7.43013572e-312, 6.27463370e-322],
        [0.00000000e+000, 0.00000000e+000],
        [4.45047875e-308, 5.30276956e+180],
        [1.57076922e-076, 4.57311095e-071],
        [3.45932221e-086, 3.35660023e-143]],

       [[6.01433264e+175, 6.93885958e+218],
        [5.56218858e+180, 3.94356143e+180],
        [5.49072739e+174, 1.68881420e+160],
        [1.43471357e-051, 8.32412919e-071],
        [5.18159126e-143, 1.50008929e+248]]])

In [19]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [22]:
float_arr2 = arr2.astype(np.float64)

In [23]:
float_arr2

array([[54.,  6., 34., 23.],
       [23., 67., 34.,  2.]])

In [24]:
arr2/2


array([[27. ,  3. , 17. , 11.5],
       [11.5, 33.5, 17. ,  1. ]])

In [25]:
arr2

array([[54,  6, 34, 23],
       [23, 67, 34,  2]])

In [26]:
arr2[1]

array([23, 67, 34,  2])

In [27]:
arr2[1,2]

34

In [36]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [37]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [41]:
arr3d.size


12

In [45]:
arr3d[:,:,1]

array([[ 2,  5],
       [ 8, 11]])

In [31]:
arr3d[1,1,2
     ]

12

In [32]:
arr2


array([[54,  6, 34, 23],
       [23, 67, 34,  2]])

In [33]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [34]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
arr2d[:2
     ]

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
ok = np.arange(5)

In [37]:
ok

array([0, 1, 2, 3, 4])

In [38]:
ok[0:3]

array([0, 1, 2])

In [39]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [42]:
arr2d[:2, 1:] = 0

In [43]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [44]:
arr =  np.empty((8,4))

In [45]:
for i in range(8):
    arr[i] = i

In [46]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [47]:
arr[[4,2,1,3]]

array([[4., 4., 4., 4.],
       [2., 2., 2., 2.],
       [1., 1., 1., 1.],
       [3., 3., 3., 3.]])

In [48]:
arr[2]

array([2., 2., 2., 2.])

In [49]:
arr[[-3,-2,-4,-6]]

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [4., 4., 4., 4.],
       [2., 2., 2., 2.]])

In [50]:
arr = np.arange(32).reshape((8,4))

In [51]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [53]:
arr[[3,5,2,6],[0,2,1,3]]

array([12, 22,  9, 27])

In [55]:
arr.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [9]:
xarr = np.array([1.0,2.3,3.4,4.5,5.6])

In [10]:
yarr =  np.array([5.0,6.3,7.4,8.5,8.6])

In [11]:
cond =  np.array([True,False,False,True,True])


In [12]:
result = np.where(cond, xarr, yarr)

In [13]:
result


array([1. , 6.3, 7.4, 4.5, 5.6])

In [15]:
arrr = np.random.randn(4,4)

In [16]:
arrr

array([[ 0.08355652,  0.09626601,  0.57216368, -1.04515944],
       [ 1.03757769,  1.36791243,  0.17552411, -1.46860657],
       [-0.65761263, -1.50789708, -0.95621816,  0.17820265],
       [-0.16893368,  0.15590071,  1.6729674 , -2.36427003]])

In [19]:
result1 = np.where(arrr<0, 5, arrr)

In [20]:
result1

array([[0.08355652, 0.09626601, 0.57216368, 5.        ],
       [1.03757769, 1.36791243, 0.17552411, 5.        ],
       [5.        , 5.        , 5.        , 0.17820265],
       [5.        , 0.15590071, 1.6729674 , 5.        ]])

In [21]:
result1.mean()

2.521254449704661

In [22]:
np.mean(result1)

2.521254449704661

In [23]:
np.sum(result1)

40.340071195274575

In [24]:
result1.max()

5.0

In [25]:
np.save('my file', result1)

In [26]:
np.load('my file.npy')

array([[0.08355652, 0.09626601, 0.57216368, 5.        ],
       [1.03757769, 1.36791243, 0.17552411, 5.        ],
       [5.        , 5.        , 5.        , 0.17820265],
       [5.        , 0.15590071, 1.6729674 , 5.        ]])

In [29]:
arrtxt = np.loadtxt('array.txt', delimiter = ',')

In [30]:
arrtxt

array([[ 0.580052,  0.18673 ,  1.040717,  1.134411],
       [ 0.194163, -0.636917, -0.938659,  0.124094],
       [-0.12641 ,  0.268607, -0.695724,  0.047428],
       [-1.484413,  0.004176, -0.744203,  0.005487],
       [ 2.302869,  0.200131,  1.670238, -1.88109 ],
       [-0.19323 ,  1.047233,  0.482803,  0.960334]])

In [31]:
arrtxt.mean()

0.14786779166666666

In [32]:
arrtxt.sum()

3.548827

In [8]:
np.linspace(0,101,10)

array([  0.        ,  11.22222222,  22.44444444,  33.66666667,
        44.88888889,  56.11111111,  67.33333333,  78.55555556,
        89.77777778, 101.        ])

In [9]:
np.arange(12).reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])